#!/usr/bin/perl -w
# Convert tab-separated text to JSON
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2011-10-31
use strict;
use JSON;

my $header = <>;
chomp $header;
my @names = map { s/\s/_/g; lc; } split /\t+/, $header;

my @records;
while (my $line = <>) {
    chomp $line;
    my $r = {};
    my @values = split /\t+/, $line;
    $r->{$_} = shift @values foreach @names;
    push @records, $r;
}

print encode_json \@records;
