#!/usr/bin/env bash
# Author: Jaeho.Shin@Stanford.EDU
# Created: 2011-10-25
set -eu

Self=`readlink -f "$0"`
Base=`dirname "$Self"`
PATH="$Base:$Base/../util:$PATH"

cd "$Base"/../data

# fetch fresh dblp.xml.gz
fetch http://dblp.uni-trier.de/xml/dblp.xml.gz
fetch http://dblp.uni-trier.de/xml/dblp.dtd

# extract data for conferences and also venue and time
{
    gunzip |
    sed -ne '1,/<dblp>/p; $p; /<proceedings .* key="conf\/.*">/,/<\/proceedings>/ { p; }' |
    xslt "$Base"/extract-from-dblp.xsl
    #cat >dblp.proceedings.xml
    #<dblp.proceedings.xml \
} <dblp.xml.gz >past-conferences.xml
