#!/usr/bin/env bash
# Author: Jaeho.Shin@Stanford.EDU
# Created: 2011-10-25
set -eu

Self=`readlink -f "$0"`
Base=`dirname "$Self"`
PATH="$Base:$Base/../util:$PATH"

set -x
fetch-confy
fetch-dblp
refine-geocodes
jsonize <data/conferences.tab >data/conferences.json
