#!/usr/bin/env bash
# Author: Jaeho.Shin@Stanford.EDU
# Created: 2011-10-28
set -eu

Self=`readlink -f "$0"`
Base=`dirname "$Self"`
PATH="$Base:$Base/../util:$PATH"

cd "$Base"/../data

[ -r geonames.org-username ] || { echo "Create data/geonames.org-username!" >&2; false; }

# first, tabularize
{
xslt "$Base"/tabularize.xsl <past-conferences.xml
xslt "$Base"/tabularize.xsl <upcoming-conferences.xml | tail -n +2
} >raw.tab
head -n 1 <raw.tab >raw-head.tab
wc -l raw.tab

if [ -e geocodes.tab ]; then
    echo geocodes.tab: already exists, skipping...
    wc -l geocodes.tab
else
    # then, extract header and where column
    {
        cut -f4 | sort | uniq -c | sort -nr | cut -b 9-
    } <raw.tab >raw-wheres.tab
    # and try geocoding them using geonames.org
    java -cp `cd "$Base"/geocode/geonames.org && for j in . *.jar; do echo -n ":$PWD/$j"; done` \
        GeocodeToponyms "`cat geonames.org-username`" \
        raw-wheres.tab | tee geocodes-geonames.org-raw.tab
    sort -t'	' -k 1 <geocodes-geonames.org-raw.tab >geocodes-geonames.org.tab
    cat geocodes-geonames.org.tab >geocodes.tab
    # combine missing ones with http://www.gpsvisualizer.com/geocoder/
    read -p "Try http://www.gpsvisualizer.com/geocoder/ for raw-wheres.tab and save it as geocode/gpsvisualizer.csv"
    sed '1d; s/,/	/; s/,/	/; s/,-,$//; s/"//g' <../geocode/gpsvisualizer.csv | sort -k 3 >geocodes-gpsvisualizer.tab
    join -t'	' -a 2 -v 2 -1 1 -2 3 -o 2.3,2.1,2.2 geocodes-geonames.org.tab geocodes-gpsvisualizer.tab >>geocodes.tab
    wc -l geocodes.tab
    echo "Where	Latitude	Longitude	City	Country" >geocodes-head.tab
fi

# finally, join them to create the final result
(
    LC_ALL=C
    format=1.1,1.2,1.3,2.2,2.3,1.5,1.6,1.4,2.4,2.5,1.7
    sort -t'	' -k 4 <raw.tab >raw.tab.sorted
    sort -t'	' -k 1 <geocodes.tab >geocodes.tab.sorted
    join -t'	' -1 4 -2 1 -o "$format" raw-head.tab geocodes-head.tab
    join -t'	' -1 4 -2 1 -o "$format" -e "" raw.tab.sorted geocodes.tab.sorted
) >conferences.tab
wc -l conferences.tab

# TODO convert it to JSON?
